name: ci-lint

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "20 4 * * 0"

jobs:
  test:
    runs-on: docker
    container:
      image: fedora:42  # lock to *latest stable*; rawhide/next is 'latest' tag
    steps:

      - name: nodejs/git/pip
        run: |
          echo -e 'max_parallel_downloads=20\ndeltarpm=False\nfastestmirror=False' | tee -a /etc/dnf/dnf.conf
          dnf -yq --no-docs --setopt=install_weak_deps=False in nodejs git-core python3-pip

      - uses: actions/checkout@v4

      - name: cache '.ansible/collections'
        id: cache-collections
        uses: actions/cache@v4
        with:
          path: /root/.ansible
          key: zfs_dkms-dot-ansible

      - name: ansible+collections
        run: |
          pip install --no-compile --no-deps ansible-core ansible-lint
          ansible-galaxy collection install -r meta/requirements.yml

      - run: ansible-lint
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
