name: lint

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "20 4 * * 0"

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: cache '.ansible/collections'
        id: cache-collections
        uses: actions/cache@v4
        with:
          path: /root/.ansible
          key: zfs_dkms-dot-ansible

      - run: ansible-galaxy collection install -r meta/requirements.yml

      - run: ansible-lint
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
