name: ci-lint

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "20 4 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest  # tag on runner maps to 'node:20-bookworm' image
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: 'pip'

      - name: ansible/collections
        run: |
          pip install ansible-core ansible-lint
          ansible-galaxy collection install -r meta/requirements.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: ansible-lint
        run: |
          ansible-lint
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
